= MIXED REALITY : Emerging Trend in Computing.

“Tom just came out from the corner. Jerry is still in the small hole in the wall. Tom is waiting for Jerry to get outside.. At last the wait is over Jerry ran out of the hole and Tom is chasing him..”. Yes, it is the same old Tom and Jerry animation and you might be wondering what is new in this. Within the next few years, you will be able to view these characters in your room running around, interact with them and view them as if the story happens in their own surrounding space. We are talking about the emerging technology – MIXED REALITY, the new buzzword in the industry.

A blend of computer generated graphics and the physical notions of time and space, the virtual reality, gained popularity in the past few years with the release of optical head mount (OHM) devices like the Oculus Rits and the Google Glass but their interaction with the user's physical space is still limited in many ways. They way how humans perceive digital graphics and real world objects differ and so, the user will easily differentiate between them, how well we mix them. The virtual, visual, haptic as well as tactile feedback that is given to the users are not good enough to build a notion of virtually real and really virtual space as the computer creativity always stands apart.

Keeping the virtual over the real world will always make the virtual part more unrealistic and hence will never give the user a good interaction experience. But what if we can merge the images virtually generated by a computer over the user's view of his surroundings? This is what the concept of Mixed Reality is all about. Merging them so well that the user will perceive the Computer Graphics as if they are a part of the real world around him. This will help users to interact with the virtuality as if it is a part of the reality surrounding them.

The Microsoft Corporation recently released their demo version of their Windows 10 based gadget, The HoloLens. HoloLens is an untethered, standalone, holographic computer, introduced as a head mount device. It uses a brand new concept where the computer generated virtual entities are projected as holograms rather than pure images. Hence the users will be able to view them as if they are three dimensional entity placed in the physical world surrounding them. And more astonishing is the fact that the device is able to recognize the contours of the objects near the user and customizes the display to fit the surroundings so that the user is able to view a customized copy of the displays rather than the real ones that may not fit into their reality. This customization principle is being used in developing highly customizable games. Imagine playing Minecraft on your tabletop, it is possible.

Ever since its launch, HoloLens captured attention of technologists all around the globe. Thanks to the great brains behind HoloLens who not just created a masterpiece but also triggered a new field of research. HoloLens is the first gadget of its kind. The limited battery life and narrow field of view can be thought of as limitations but will definitely be answered soon. The future is bright and promising. The gadgets like Project Tango, which maps the things around, using the combination of a camera, IR sensors and depth sensors in pure three dimensions and the project Soli which improves the gesture recognition by delicate hand-motion sound-recognition, the future of digital revolution is very much promising. One day, human race will be waking up into a world where computing world and the real physical space co-exist, where they cannot be separated. Also the other companies including many startups have started their research in this field. Mixed Reality is not really real, nor it is really virtual. This property of seamless mingling of the objects both real and virtual can help develop devices that can be used for study and research. NASA has put HoloLens in their research labs where the scientists use the rover generated images of Mars to view the surface of Mars as if they were actually physically present there. The design capabilities of such devices are awesome as its processing capabilities are beyond the usual mobile Optical Head Mount Devices.

Microsoft Corporation is looking forward for a wide release of this Mixed Reality device within the Windows 10 time frame. Since more products and innovations happen in the digital world every second, there will be more products of this type soon available in the market, targeting small kids as well as elders. The proposed ideas of the fifth generation of computing where artificial intelligence is becoming stronger will get a thrust forward with this kind of devices coming up. The trend is changing. And so is the technology. Anyway it is evident that in the next 20 years, we will transform into a digitalized life, different from where we are now and this is just a beginning.

*This Article was published in the first edition of IEEE Compute | The IEEE Computer Society India Council Student Activities Newsletter. The actual article may vary from this unedited version. IEEE Compute is available for download at anandjagadeesh.github.io/ieeecompute*