= Reading Between The Bits

The binary number system uses '10' digits and all are aware of this fact. The two digits are nothing but '0' that is used to represent a low voltage and '1' which represents a high voltage. The world of computers is where the mathematics of bits gives life to the chip sets that are, otherwise just pieces of silicon. A lot of things have changed over the years. The e-mails replaced postcards, the e-books replaced the bulky prints, and thus bit by bit our world is being transformed. And the buzzwords of the computing world have changed from e-mails, graphics and portable to big-data, analytics, qubits and IoT. Yes, the notion of computing is changing day-by-day. The world of computing has changed from big bulky factory-like machines to palm-sized and interconnected entities. And the amount of calculations that we need the computer to do for us have grown millions of times more. The efficiency of computing is evaluated based on its ability to solve the complex calculations in the minimum latency. Researchers are trying to develop technologies that can outrun the existing ones and get the best results in the minimum possible time.

*Quantum Computing*

The quantum computing studies about the possibilities of using the quantum-mechanical phenomena such as superposition and enlargement directly to operate upon data. The digital computers use data encoded in binary. The quantum computers are capable of handling the binary states as well as their superposition. This means that they are capable of handling the states where the two states coexists. They are a group of computers that share a lot of theoretical similarities with non deterministic and probabilistic computers. Initiated by the studies of Yuri Manin, Richard Feynman and David Deutsch in the 1980 had always been a field of interest for many tech-giants and computer enthusiasts.

The development of actual quantum computers is still in its infancy and operations were carried out only on a few quantum bits. But a lot of governmental and non governmental agencies are conducting as well as funding the researches on the development and actual implementation of these next generation computing technologies. The main problem is that quantum computing is a very fragile process and will be thrown off by vibrations, light and temperature variations. The scientists are trying to bring the error rate down so as to match, at least, the present age digital computers. Because of the complexity and sensitivity, research should also focus upon detecting and correcting the errors and changes that occur so that they can get around them next time or correct them instantly. However, it is believed that the large scale quantum computers will be able to solve certain problems much more quickly than any classical computers that use even the best currently known algorithms, like integer factorization using Shor's algorithm or the simulation of quantum many body systems. There exist quantum algorithms, such as Simon's algorithm, that run faster than any possible probabilistic classical algorithm.

A Qubit, in a quantum machine can be a one and a zero at the same time. When a qubit is built, we cannot predict that whether it will be a one or a zero. A qubit has the possibility of being positive in one calculation and negative in another. Each qubit changes based on its interaction with other qubits.

*The Main Hurdles*

Quantum computing, still a rather mysterious technology, combines both computing and quantum mechanics, which is one of the most complex, and baffling, areas of physics. The method to detect and correct errors is the main problem that remains in the path of developing the quantum computers. All qubits suffer from the fact that the quantum effects they use to represent data are very susceptible to interference. Much current work is focused on showing that small groups of qubits can detect when errors have occurred so they can be worked around or corrected.

A group of researchers from the University of California were able to create an array of nine superconducting qubits and a few qubits in the system were able to detect bit flips, an error where a qubit flips its state – from 0 to 1 or from 1 to 0, in their fellow qubits. Another error that may occur in qubits is the phase flip where the superposition state becomes distorted, which can be detected only when qubits work in a matrix or 2D array.

Another problem is the low operating temperatures. Most of the research models and the practical ones are running at temperatures close to absolute zero or the 0K mark. The lower operating temperature enhances the importance of quantum effects, which increases the ability to discriminate the best result from a collection of good candidates. A fourth problem is the noise and interference conditions. The best results can never be obtained unless the noise and interference that may cause errors in the quantum computation are reduced. The lower noise environment enhances problem-solving performance while boosting reliability and stability. A fifth problem is control circuitry precision, as the precision of the other factors is determined by the control circuitry. That is not it. A lot of other features and characteristics of quantum mechanics are causing hindrance in the development of this technology.

*The Future is Bright*

The Quantum Computing have many hi-fi applications, but the development is hindered by the problems of quantum mechanics itself. If we can answer these problems, we will definitely end up with the best ever problem solver. Some problems that will take years to get completed on the digital computers will be completed in a few seconds on the quantum computer. The qubits arranged together are physically seperate entities, but are all connected, hence corrections to one can put every other qubit to fall in place correcting errors as a qubit changes based on its interaction with other qubits.


The future quantum computers will find their place in handling and manipulation of big data, performing searches for patterns with a speed that outruns most of the modern digital high performance supercomputing facilities. They will also be applied in the fields of microbiology, study of pathogens, medicinal applications and astronomy. Scientists have predicted quantum computing models to be used for medicinal researches that would someday lead to finding cures for cancers and other diseases. The quantum computing can also be used in astronomy where they can be used to discover and study distant planets, taking advantage of their speed in calculations, which will take years to be solved in digital computers. Quantum computing is still a rather mysterious technology, combines both computing and quantum mechanics, which is one of the most complex, and baffling, areas which constitute a branch of physics, that evolved out of an effort to explain things that traditional physics is unable to. With the advancement of technology and the involvement of the tech-giants like IBM, Google, Microsoft and D-Wave in the field of Quantum Computing, funding as well as conducting researches is very much promising as this is the future of computing we are heading to. The future is bright and let us hope that quantum computers will replace the digital high performance computers in the near future and the digital computers will become a part of the fifth generation computing's history page.