= The place that is changing my perspectives

I want to share the news that I joined a prestegious group two weeks back. And I also want to share the experience I had there for the past few days, which of course is the best I ever had in FISAT. I joined the High Performance Computing Research group of FISAT two weeks before, which comes under the Centre for High Performance Computing (CHPC) under the Department of Computer Science and Engineering (DoCSE). The group is mentored by Mr. Mahesh C., Assistant Professor in DoCSE. Let me share what I experienced.

==== How it all started..

From the first orientation session we had, we heard the name CHPC many times from our HoD, Dr. Prasad and from all the people who came to introduce us to DoCSE. Later when we started using the labs, I saw a bunch of racks behind the glass windows near the System Administrator's room, which I later heard, as the High Performance Computing System called the Dakshina Cluster. And to my amazement, every thing was in a room say approximately 2mX5m, different from what we see in internet, where there will be huge computers. In my fourth semester, during the activities of the Industry Institute Partnership Cell, I met the architect of the Dakshina Cluster, Mr. Mahesh C. In my fifth semester, we had an industrial training under the CHPC with lot of industry people for training us. Later we had a test for CHPC and we were shortlisted for the interview.

==== The very first day at CHPC

The first day, we had an interaction with two of our alumni, Mr. Vivek and Mr. Anil. They shared with us, the experience they had at CHPC and how it helped them in advancing their career. We were really enthusiastic to talk to them. And they desribed all about the possibilities we have and about the responsibilities and duties that we need to take up once we are in the team. Then Mr. Mahesh C. explained about the team and what we have to do.

==== Changing perspectives

In the days that followed, we had classes at 7:30 am in the morning and it was awesome. Initial days, I felt it really tough to wake up at 5 am and get ready, but later on it was really amazing. We started with Signals. And every day I had a new thing to think about. We learned the theory in textbooks. But we never realized what these things were. All we had to do was to learn in the exam point of view. But everyday Mahesh sir talked about things we already knew, but none could explain it in the correct way. We new the textual definitions, but never really knew what it is. Every time sir explained a topic, or made us find answers by ourselves, we learned what it is. It really changed my perspectives about learning.

Another major happening in the past week was an interactive session by Dr. Roshy John, Head of Robotics and Cognitive Systems, Tata Consultancy Services. He is the man behind the autonomous Nano car that triggered the autonomous vehicle revolution in India. We were able to interact with him and learn a lot of things about the autonomous vehicle he designed and robotics and its evolution in India.

I have just entered the research team, but even in this short span of time, the team helped me in learning a lot of things. It helped me in changing my perspectives about learning new things. I believe that the coming semester will be the best one I'll ever have.