= How I Cracked My First Interview : The Ten Principles I Followed

I attended the placement drive by Tata Consultancy Services on the 21st and 22nd of September, 2016 at my college, Federal Institute of Science And Technology (FISAT), Angamaly. I received mails and messages that asked me what they asked me during the Personal Interview. So, I thought I have to share the Ten Principles (of course, there are many principles that I used. But since it is a common thing that everyone posts "The ten things I did..", I just adopted the same thing.. :-) ) that helped me crack my First Interview.

== The TCS Selection Process

Before I begin, let me give a brief introduction to the process of campus placements that TCS followed in our campus. A student have to go through six stages. First is just the basic eligibility criteria, 60% (6.5 CGPA) in B. Tech., XII and X and only one standing backlog. Second the Aptitude Test. Luckily, I had CGPA above 8.1 and so, I was in the Aptitude Test exemption category. Third, the Verbal Test. I cleared it. If you are a good coder, attend Code Vita and be in the top 1500 and you don't have to write the verbal too. The fourth one is the Technical Interview Round, fifth, the Managerial Interview Round and the sixth, the HR Interview Round. And if you clear all this, you'll get an offer letter. Yippiee..!!

== The Ten Principles

Ok. So, let me start. Some of these sound like what your teachers and trainers tell you. But yaar, it works.

==== 1. Be Confident

This is the first rule. If you prepare too much, you'll ruin the interview. You are superb. And better than thousands out there. So. Be confident. You are fit for the job. Don't let it slip away.

==== 2. Be Truthful

Always tell the truth. If you are lying, you will get caught somewhere or the other. Tell only things you do posess, be it skills or certifications. Even if you don't get placed, you'll not loose your self respect.

==== 3. Don't Think Too Much

Be spontaneous with your answers. Let them pour out from your heart. When you express what your heart has to say, you will not take much time to think and this will make you unique. But do not prepare for questions, mug up answers and vomit. Again, you will end up in trouble.

==== 4. Be Sincere, Not Serious

Being Sincere doesn't mean that you have to be serious. Just chill. This is no University exam to get tensed. If not this, You'll get the next one.

==== 5. Don't Over React

The process will even lead you to a state where you have to wait hours. Also selection in one of the first five rounds will not get you a job. Consider each stage seriously. Every step is crucial. If you clear the HR Round. CELEBRATE..!!

==== 6. Know Yourself Well

You must know who you are and what you are capable of. You should know about yourself, your strength and weaknesses, because this will stab you from behind if you do not handle them right. Introspect! Introspect! Introspect!

==== 7. Never Try To Impress The Interviewers

They will be impressed automatically if you are good in technical, MR and HR. You do not have to put extra effort, trying to impress the Interviewer. Sometimes, it will put you in trouble. So, Beware!

==== 8. Know Your Employer

Research about your employer before you attend their placements. It will help you in tweaking the answers for the company's requirements.

==== 9. Think Twice Before You Speak

Sounds contrasting to point Three? No. Its not. Think before you answer because, some questions will be asked to pin you down. And blunders will help you get rejected! So think before you answer bro, but don't think too much.

==== 10. Do Not Underestimate Your Powers

Whatever you have done, it is the best and unique thing. Believe in it. And project them as is. Sometimes, things you think are the worst, will be what the eployer requires.

Let me stop this for now. More queries? Feel free to comment below or mail it directly to me at: janand.online@gmail.com

Thanks for your patience!