= The user friendly computer programs.

Writing computer programs is not speaking in a different language that only a programmer and a computer understands. It is, in fact, instructing a computer to do the tasks, for the end user, the way the end user wants it to happen. So, writing computer programs is not about just writing pieces of codes and running them. We need to make sure that the interfaces are easily understood by the person who use it. A good interface makes it easy for the end user to work with, but collects all relevant information required for the processing, without making the process too complicated.

A good example to start with would be a program that accepts the date of birth and prints the day alone. Let the python code be:

 p=input("DoB: ")

Here, a prompt will be given as

 DoB:

The user can enter the DoB in many formats:

 DoB: 13-07-2017
 
or 

 DoB: 13/07/2017

There are plenty of options. So, what will go wrong? No standard input format for DoB is specified here. So each user enters it in a format of his choice. The programmer can write the code to parse the entered string considering all possible formats he can guess. But say the user enters 13@07@2017 and if the programmer failed to write a code to parse the string correctly for this format, the program fails. This option of writing a code that gives the user maximum freedom is good but it is too difficult to implement. So another option is to specify a format for entering the DoB as in:

 p=input("Please enter your DoB in the format dd/mm/yyyy here: ")

This sounds better. No? This helps the user to enter the DoB in a specific format and also the programmer to code to identify only one format.