= "Why did you do that?"

 What are you talking about?

This is about asking questions. Yes, asking questions. Suppose you have a very important responsibility on your shoulder. You are responsible for the decisions you take, no? We are answerable for what we do when we hold a responsible position or in-charge of some task or someone entrust you with something. Say, you did something that you thought would yield positive results. But, unfortunately something didn't work out correctly and the results were terrible. For example, let's say you are the project lead building an operating system. You thought there is no need for a backdoor for the engineers to enter the system and shutdown the system during an execution or programming turning into a catastrophe, because you thought such a backdoor would involve the user's privacy and can be misused. You might be correct in your judgement/viewpoint. But say, a catastrophe happened and the unavailability of such a backdoor resulted in a lot of losses to a customer.

See, here what you did was right from your angle. Since a catastrophe happened, people will turn to you and ask why you didn't put a backdoor in the system. You have a perfect reason for what you did. If you present it well, others will also accept it and they will also feel it was a right decision, right(if they didn't, you are in deep trouble)? That's what reasons and justifications are for. You might be thinking why I am talking all this nonsense. Yes, this might sound nonsense to you but