= "Why did you do that?"

 Please read in full before jumping into conclusions! :)

This is about asking questions. Yes, asking questions. Suppose you have a very important responsibility on your shoulder. You are responsible for the decisions you take, no? We are answerable for what we do when we hold a responsible position or in-charge of some task or someone entrust you with something. Say, you did something that you thought would yield positive results. But, unfortunately something didn't work out correctly and the results were terrible. For example, let's say you are the project lead building an operating system. You thought there is no need for a backdoor for the engineers to enter the system and shutdown the system during an execution or programming turning into a catastrophe, because you thought such a backdoor would involve the user's privacy and can be misused. You might be correct in your judgement/viewpoint. But say, a catastrophe happened and the unavailability of such a backdoor resulted in a lot of losses to a customer.

See, here what you did was right from your angle. Since a catastrophe happened, people will turn to you and ask why you didn't put a backdoor in the system. You have a perfect reason for what you did. If you present it well, others will also accept it and they will also feel it was a right decision, right(if they didn't, you are in deep trouble)? That's what reasons and justifications are for. You might be thinking why I am talking all this nonsense. Yes, this might sound nonsense to you but wait just read the rest of this article before you jump into conclusions. :) "What is all this about? Why were you talking about all that?" Yes., I am coming to that. Before proceeding further. Take two minutes to think of some situation where you were asked to explain your decision. Were you able to give a convincing explanation? At least you tried to justify your part, right? You had a reason of your own. Reasoning ability is a part of most skill tests.

We are moving into an era where robots are getting employed in almost all fields. The recent improvements in artificial intelligence and machine learning is promising. We will be walking down a street in the coming years and the street's internetworked sensors and devices will be monitoring you, your health, and a hell lot of other things, the vehicles will be totally behaving autonomously, like a swarm, seamlessly connecting with each other and roaming around the road intelligently, driven by AI, much better than a human driver and a homes and everything around you becoming more and more smarter. Well, I would love to see some really intelligent systems that we have seen in sci-fi movies as a child. Yes, the future is promising. But with everything, you will get some clauses. Like a friend of mine who is a software engineer once jokingly mentioned, "nothing comes for free, even Santa's got a 'Claus(e)". Recent thoughts from a group of researchers pointed towards some of the side effects or rather can be regarded as ill effects of excessive use of Machine Learning and Deep Learning to build high end intelligent systems.

They say there were cases where a driverless or autonomous car stopped at a green light, run through a red light